apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
# user and password has to be in base-64 encode
# run on termina: echo -n user_name | base64
  mongo-user: c2F0aXNo # satish
  mongo-password: bXlwYXNzd29yZA== # mypassword